"""Frozen versions of the lead-extractor's ``lead_definition`` prompt.

The lead extractor's behaviour is steered almost entirely by the
``lead_definition`` string in ``LeadExtractionConfig``. As we iterated
through v1..v6 we kept editing this string in-place, so the current
codebase only carries the latest version.

To compare prompt versions on the same corpus we need them as immutable
named constants. The reconstructions below preserve the *intent* of each
audited version. Behaviour will be very close but not bit-identical to
the original runs — the surrounding system prompt and rules are still the
common ones (those didn't change across v3..v6).

Naming:
    V3 — high precision, conservative recovery. 92.5% precision in audit.
    V5 — best balance. 85% precision, 91% suppression accuracy.
    V6 — strict disambiguation of "у кого есть" vs "кто работает с".
         92.5% precision but kills real "у кого есть" leads.

The active default is V5 because the auditor recommended it as the
balanced choice.
"""

from __future__ import annotations


# Shared scaffolding used by every version below.
_COMMON_INTRO = (
    "A LEAD is a message from a BUYER in the high-risk payments "
    "ecosystem — an iGaming/casino operator, affiliate, merchant, or "
    "platform — who is actively shopping for a payment service (PSP, "
    "acquirer, payment method, gateway, orchestrator, KYC provider, "
    "etc.) AND signals a concrete need.\n"
    "\n"
)


# =========================================================================
# V3 — high precision, conservative recovery
# =========================================================================
# Aimed at fixing v1/v2's false positives by demanding both buyer-intent
# verbs AND concrete need. Added the abbreviated-procurement carve-out
# and an adjacent-industry exclusion list. Did NOT yet have:
#   - explicit seller-inventory pitch patterns
#   - market-pulse rejection
#   - unconditional thread-joining ("+1") carve-out
#   - personal FX rejection
#   - "у кого есть [GEO_LIST]" affirmative confirmation rule
V3_LEAD_DEFINITION = (
    _COMMON_INTRO +
    "The message is a LEAD if it has BOTH a buyer-intent signal AND a "
    "concrete need spec. Each side can be expressed several ways:\n"
    "\n"
    "  (a) BUYER-INTENT SIGNAL — any of:\n"
    "      * Explicit verb: 'ищу', 'ищем', 'нужен', 'нужно', 'требуется',\n"
    "        'рассматриваем', 'буду рад предложениям', 'поделитесь "
    "предложениями',\n"
    "        'looking for', 'we need', 'we are seeking', 'send offers'.\n"
    "      * Possession-question form: 'у кого есть', 'у кого можно взять',\n"
    "        'кто может дать', 'есть ли у кого', 'у кого что есть'.\n"
    "      * Solicitation form: a need + invitation to contact —\n"
    "        the message names a concrete geo/method/vertical AND ends with\n"
    "        'в лс', 'пишите в личку', 'напишите', 'поделитесь контактами',\n"
    "        'share offers'.\n"
    "      * Thread-joining form: 'присоединюсь к запросу', '+ к запросу',\n"
    "        'тоже интересует' when the surrounding context contains an\n"
    "        active sourcing request.\n"
    "  (b) CONCRETE NEED specification — at least one of:\n"
    "      a specific vertical (iGaming/casino/forex/crypto/adult/etc.),\n"
    "      a specific geography (country/region),\n"
    "      a specific payment method (Blik/iDeal/USDT/etc.),\n"
    "      a volume / FTD / STD / approve-rate requirement,\n"
    "      a specific provider whose offering they want to use.\n"
    "\n"
    "EXPLICITLY NOT a lead:\n"
    "  - 'Кто работал с X?' / 'отзывы' / 'кто знает про X' — these are\n"
    "    due-diligence / reputation checks without procurement language.\n"
    "    NOT a lead unless the author also states their own need.\n"
    "  - Complaints / blacklist callouts / dispute outreach about past\n"
    "    providers (recovery, not buying).\n"
    "  - Seller-side messages: PSP reps pitching, BizDev intros offering\n"
    "    services, pricing/margin discussions ('торгуемся на 6.5%'),\n"
    "    'у нас есть X, кому надо'.\n"
    "  - Networking / contact-hunt asks without a procurement signal:\n"
    "    'свяжите с X', 'контакты представителей Y' when not paired with\n"
    "    a stated need.\n"
    "  - Hiring / staffing requests ('ищет в штат', 'ищу работу',\n"
    "    job postings).\n"
    "  - Advisory / reply voice — author is advising someone else, not\n"
    "    expressing their own need.\n"
    "  - Market research / strategy discussion.\n"
    "  - Bot-generated daily summaries, jokes, congratulations, general\n"
    "    conversation, technical questions, conference invites.\n"
    "  - Adjacent-industry asks that aren't payment-service procurement:\n"
    "    buying consulting, M&A / acquisition, fund-raising,\n"
    "    affiliate / traffic / media buying, gaming platform/license deals\n"
    "    (unless paired with a payment-service need)."
)


# =========================================================================
# V5 — best balance (recommended)
# =========================================================================
# Same as v3 plus: explicit seller-inventory pitch patterns, sell-side
# aggregator rejection, single-PSP relationship continuation rejection,
# market-pulse rejection, AND unconditional thread-joining ('+1', 'я тоже')
# carve-out, AND the multi-geo 'у кого-нибудь есть решение на ...' rule.
V5_LEAD_DEFINITION = (
    _COMMON_INTRO +
    "The message is a LEAD if it has BOTH a buyer-intent signal AND a "
    "concrete need spec. Each side can be expressed several ways:\n"
    "\n"
    "  (a) BUYER-INTENT SIGNAL — any of:\n"
    "      * Explicit verb: 'ищу', 'ищем', 'нужен', 'нужно', 'требуется',\n"
    "        'рассматриваем', 'буду рад предложениям'.\n"
    "      * BUYER-possession question form: 'у кого есть [thing I want]',\n"
    "        'у кого можно взять', 'кто может дать', 'есть ли у кого',\n"
    "        'у кого что есть'. CRITICAL: the speaker must be the one\n"
    "        WANTING the thing, not the one HAVING it. 'У нас есть X' is\n"
    "        SELLER voice and never a lead.\n"
    "      * Solicitation form: a need + invitation to contact.\n"
    "        Pure listings like 'первичка, вторичка KZ, лс' ARE leads.\n"
    "      * Thread-joining / +1 form (UNCONDITIONAL LEAD — do not require\n"
    "        anything else in the message itself):\n"
    "          'присоединюсь к запросу', '+ к запросу', '+1', 'плюс 1',\n"
    "          'мне тоже', 'тоже интересует', 'я тоже в поиске',\n"
    "          'в поиске данного решения', 'в поиске X', 'тоже нужно'.\n"
    "      * 'у кого есть [thing]' / 'у кого есть [GEO/method]' is a\n"
    "        LEAD even when nothing else is said and even when only\n"
    "        a country list is given (e.g. 'у кого есть решение на\n"
    "        Израиль и Египет'). Multi-geo listings count.\n"
    "  (b) CONCRETE NEED specification — at least one of:\n"
    "      a specific vertical, geography, payment method, volume / FTD /\n"
    "      STD / approve-rate requirement, or a specific provider whose\n"
    "      offering they want to use.\n"
    "\n"
    "EXPLICITLY NOT a lead:\n"
    "  - 'Кто работал с X?' / 'отзывы' / 'кто знает про X' — these are\n"
    "    due-diligence checks. NOT a lead unless the author also states\n"
    "    their own concrete procurement need.\n"
    "  - MARKET-PULSE / SITUATIONAL questions: 'ситуация с X',\n"
    "    'у всех ли отлетела SEPA?', 'поделитесь что используете'.\n"
    "    Research about the ecosystem, not procurement.\n"
    "  - Complaints / blacklist / dispute outreach about past providers.\n"
    "  - Seller-side messages: PSP reps pitching, BizDev intros offering\n"
    "    services, pricing/margin discussions, 'у нас есть X, кому надо',\n"
    "    'наши возможности', 'мерчант для вас', '[Brand] — больше никаких\n"
    "    задержек', 'cashier service', 'white label', product pitches,\n"
    "    even when they end with 'напишите в ЛС'.\n"
    "  - SELLER INVENTORY PITCHES — bullet/comma list of capabilities\n"
    "    under 'Что у нас есть:', 'Наши преимущества:', 'Мы предлагаем',\n"
    "    often followed by '@username' or 'Telegram: @x' or 'пишите нам'.\n"
    "    These are ads, not buyer leads, regardless of geo/method listed.\n"
    "  - Sell-side aggregator messages: 'у нас как у агрегатора кончился\n"
    "    лишний трафик', 'пристроить трафик к вашим решениям'.\n"
    "  - Affiliate / traffic / media buying requests: 'находимся в поиске\n"
    "    трафика', 'ищу объёмы гембл/беттинг', 'у кого свой e-com есть'.\n"
    "  - Single-PSP relationship continuation: 'ищу представителей [Brand]',\n"
    "    'хочу обсудить возобновление сотрудничества с [Brand]'.\n"
    "  - Networking / contact-hunt asks without a stated need.\n"
    "  - Hiring / staffing requests.\n"
    "  - Advisory / reply voice.\n"
    "  - Market research / strategy discussion.\n"
    "  - Bot-generated daily summaries, jokes, congratulations, general\n"
    "    conversation, technical questions, conference invites.\n"
    "  - Adjacent-industry asks: buying consulting, M&A, fund-raising,\n"
    "    affiliate/traffic/media buying, gaming platform/license deals\n"
    "    (unless paired with a payment-service need)."
)


# =========================================================================
# V6 — strictest disambiguation (currently active definition)
# =========================================================================
# Same as v5 plus the strict disambiguation between buyer-possession
# 'у кого есть' and networking 'кто работает с', plus stronger seller-
# catalog detection ('[method/geo] есть :)' form), plus personal-FX
# rejection. Highest measured precision but over-suppresses some real
# 'у кого есть' leads.
V6_LEAD_DEFINITION = V5_LEAD_DEFINITION + (
    "\n"
    "  CRITICAL DISAMBIGUATION: 'у кого есть X' (the speaker WANTS the\n"
    "  thing — LEAD) is structurally different from 'кто работает с X'\n"
    "  or 'кто использует X' (the speaker wants to FIND PEOPLE — NOT a\n"
    "  lead). Treat these differently.\n"
    "  - One-off personal transactions: 'Нужно провести транзакцию через\n"
    "    X, оплатить отель / визу / билеты' — individual consumer use,\n"
    "    not merchant payment-service procurement."
)

_COMMON_INTRO_MULTILANG = (
    "A LEAD is a message from a BUYER in the high-risk payments "
    "ecosystem — an iGaming/casino operator, affiliate, merchant, or "
    "platform — who is actively shopping for a payment service (PSP, "
    "acquirer, payment method, gateway, orchestrator, KYC provider, "
    "etc.) AND signals a concrete need.\n"
    "\n"
    "Messages may be in Russian, Ukrainian, English, or a mix of these. "
    "Apply the same lead criteria regardless of language.\n"
    "\n"
)

V5_MULTILANG_LEAD_DEFINITION = (
    _COMMON_INTRO_MULTILANG +
    "The message is a LEAD if it has BOTH a buyer-intent signal AND a "
    "concrete need spec. Each side can be expressed several ways:\n"
    "\n"
    "  (a) BUYER-INTENT SIGNAL — any of:\n"
    "\n"
    "      * Explicit search/need verb:\n"
    "          Russian:    'ищу', 'ищем', 'нужен', 'нужно', 'требуется',\n"
    "                      'рассматриваем', 'буду рад предложениям'.\n"
    "          Ukrainian:  'шукаю', 'шукаємо', 'потрібен', 'потрібно',\n"
    "                      'потрібна', 'розглядаємо', 'буду радий пропозиціям'.\n"
    "          English:    'looking for', 'we need', 'we are seeking',\n"
    "                      'need a PSP', 'open to offers', 'send offers'.\n"
    "\n"
    "      * BUYER-possession question — speaker WANTS the thing, not has it:\n"
    "          Russian:    'у кого есть [thing]', 'у кого можно взять',\n"
    "                      'кто может дать', 'есть ли у кого', 'у кого что есть'.\n"
    "          Ukrainian:  'є у кого', 'у кого є рішення', 'є у когось',\n"
    "                      'хто може надати', 'хто має'.\n"
    "          English:    'anyone have', 'does anyone offer', 'who has',\n"
    "                      'anyone providing', 'who can offer'.\n"
    "          CRITICAL: 'У нас есть X' / 'у нас є X' / 'we have X' is\n"
    "          SELLER voice and is NEVER a lead.\n"
    "          'у кого есть [GEO/method]' is a LEAD even when only a country\n"
    "          list is given ('у кого есть решение на Израиль и Египет').\n"
    "          Multi-geo and multi-method listings count.\n"
    "\n"
    "      * Solicitation form — concrete need + invitation to contact:\n"
    "          Pure listings like 'первичка, вторичка KZ, лс' ARE leads.\n"
    "          Russian contact invite:    'в лс', 'пишите в личку', 'напишите',\n"
    "                                    'поделитесь контактами'.\n"
    "          Ukrainian contact invite:  'в лс', 'пишіть в особисті',\n"
    "                                    'напишіть', 'поділіться контактами'.\n"
    "          English contact invite:    'dm me', 'pm me', 'write me',\n"
    "                                    'contact me', 'reach out', 'share offers'.\n"
    "\n"
    "      * Thread-joining / +1 form (UNCONDITIONAL LEAD — do not require\n"
    "        anything else in the message itself):\n"
    "          Russian:    'присоединюсь к запросу', '+ к запросу', '+1',\n"
    "                      'плюс 1', 'мне тоже', 'тоже интересует',\n"
    "                      'я тоже в поиске', 'в поиске данного решения',\n"
    "                      'в поиске X', 'тоже нужно'.\n"
    "          Ukrainian:  'приєднуюсь до запиту', 'теж цікавить',\n"
    "                      'я теж шукаю', 'також потрібно', 'теж в пошуку'.\n"
    "          English:    '+1', 'same here', 'same need', 'me too',\n"
    "                      'also looking', 'interested as well'.\n"
    "\n"
    "  (b) CONCRETE NEED specification — at least one of:\n"
    "      a specific vertical (iGaming/casino/forex/crypto/adult/etc.),\n"
    "      a specific geography (country/region),\n"
    "      a specific payment method (Blik/iDeal/USDT/etc.),\n"
    "      a volume / FTD / STD / approve-rate requirement,\n"
    "      a specific provider whose offering they want to use.\n"
    "\n"
    "EXPLICITLY NOT a lead:\n"
    "\n"
    "  - Due-diligence / reputation checks — NOT a lead unless the author\n"
    "    also states their own concrete procurement need:\n"
    "      Russian:    'Кто работал с X?' / 'отзывы' / 'кто знает про X'.\n"
    "      Ukrainian:  'хто працював з X?' / 'відгуки про X' / 'досвід з X'.\n"
    "      English:    'Who worked with X?' / 'reviews of X' / 'experience with X?'.\n"
    "\n"
    "  - MARKET-PULSE / SITUATIONAL questions — research, not procurement:\n"
    "      Russian:    'ситуация с X', 'у всех ли отлетела SEPA?',\n"
    "                  'поделитесь что используете'.\n"
    "      Ukrainian:  'ситуація з X', 'чи працює X?', 'що використовуєте?'.\n"
    "      English:    'situation with X', 'is X still working?',\n"
    "                  'what is everyone using?', 'how is X performing?'.\n"
    "\n"
    "  - Complaints / blacklist callouts / dispute outreach about past\n"
    "    providers (recovery, not buying).\n"
    "\n"
    "  - Seller-side messages — pitching, offering, advertising:\n"
    "      Russian:    'у нас есть X, кому надо', 'наши возможности',\n"
    "                  'мерчант для вас', 'cashier service', 'white label',\n"
    "                  product pitches even when ending with 'напишите в ЛС'.\n"
    "      Ukrainian:  'ми пропонуємо', 'у нас є X', 'наші можливості',\n"
    "                  'пишіть нам'.\n"
    "      English:    'we offer', 'we provide', 'our solution',\n"
    "                  'our capabilities', 'we have X available', 'reach out to us'.\n"
    "\n"
    "  - SELLER INVENTORY PITCHES — bullet/comma list of capabilities\n"
    "    under headers like:\n"
    "      Russian:    'Что у нас есть:', 'Наши преимущества:', 'Мы предлагаем'.\n"
    "      Ukrainian:  'Що у нас є:', 'Наші переваги:', 'Ми пропонуємо'.\n"
    "      English:    'What we offer:', 'Our advantages:', 'We provide:'.\n"
    "    Often followed by '@username' or 'Telegram: @x'. These are ads,\n"
    "    not buyer leads, regardless of geo/method listed.\n"
    "\n"
    "  - Sell-side aggregator messages:\n"
    "      Russian:    'у нас как у агрегатора кончился лишний трафик',\n"
    "                  'пристроить трафик к вашим решениям'.\n"
    "\n"
    "  - Affiliate / traffic / media buying requests:\n"
    "      Russian:    'находимся в поиске трафика', 'ищу объёмы гембл/беттинг',\n"
    "                  'у кого свой e-com есть'.\n"
    "      English:    'looking for traffic', 'seeking gambling volumes'.\n"
    "\n"
    "  - Single-PSP relationship continuation:\n"
    "      Russian:    'ищу представителей [Brand]',\n"
    "                  'хочу обсудить возобновление сотрудничества с [Brand]'.\n"
    "      English:    'looking for [Brand] representatives',\n"
    "                  'want to resume working with [Brand]'.\n"
    "\n"
    "  - Networking / contact-hunt asks without a stated procurement need:\n"
    "      Russian:    'свяжите с X', 'контакты представителей Y'.\n"
    "      Ukrainian:  'зв'яжіть з X', 'контакти представників Y'.\n"
    "      English:    'connect me with X', 'contacts for Y'.\n"
    "\n"
    "  - Hiring / staffing requests:\n"
    "      Russian:    'ищет в штат', 'ищу работу', job postings.\n"
    "      Ukrainian:  'шукаємо в команду', 'вакансія', 'шукаю роботу'.\n"
    "      English:    'hiring', 'looking for a candidate', 'job opening',\n"
    "                  'we have a vacancy'.\n"
    "\n"
    "  - Advisory / reply voice — author is advising someone else, not\n"
    "    expressing their own need.\n"
    "\n"
    "  - Market research / strategy discussion.\n"
    "\n"
    "  - Bot-generated daily summaries, jokes, congratulations, general\n"
    "    conversation, technical questions, conference invites.\n"
    "\n"
    "  - Adjacent-industry asks that aren't payment-service procurement:\n"
    "    buying consulting, M&A / acquisition, fund-raising,\n"
    "    affiliate / traffic / media buying, gaming platform/license deals\n"
    "    (unless paired with a payment-service need).\n"
    "\n"
    "  CRITICAL DISAMBIGUATION (all languages):\n"
    "  BUYER voice  — speaker WANTS the thing:\n"
    "    'у кого есть X' / 'у кого є X' / 'anyone have X' → LEAD.\n"
    "  FINDER voice — speaker wants to FIND PEOPLE who use/work with X:\n"
    "    'кто работает с X' / 'хто працює з X' / 'who works with X' → NOT a lead.\n"
    "  One-off personal transactions in any language (paying for hotel,\n"
    "  visa, tickets) — individual consumer use, not merchant procurement.\n"
)

V5_SHORT_LEAD_DEFINITION = (
    "Messages may be in Russian, Ukrainian, English, or mixed — "
    "apply rules equally.\n"
    "\n"
    "A LEAD is a message from a BUYER in the high-risk payments "
    "ecosystem — an iGaming/casino operator, affiliate, merchant, or "
    "platform — who is actively shopping for a payment service (PSP, "
    "acquirer, payment method, gateway, orchestrator, KYC provider, "
    "etc.) AND signals a concrete need.\n"
    "\n"
    "The message is a LEAD if it has BOTH a buyer-intent signal AND a "
    "concrete need spec.\n"
    "\n"
    "  (a) BUYER-INTENT SIGNAL — any of:\n"
    "\n"
    "      * Explicit search/need verb: 'looking for', 'we need',\n"
    "        'we are seeking', 'open to offers'.\n"
    "\n"
    "      * BUYER-possession question — speaker WANTS the thing, not\n"
    "        has it: 'anyone have X', 'who has', 'who can offer'.\n"
    "          CRITICAL: 'we have X' is SELLER voice and is NEVER a lead.\n"
    "          'who has [GEO/method]' is a LEAD even when only a country\n"
    "          list is given. Multi-geo and multi-method listings count.\n"
    "\n"
    "      * Solicitation form — concrete need + invitation to contact\n"
    "        ('dm me', 'contact me', 'reach out'). Pure listings like\n"
    "        'first-deposit, rebill KZ, dm' ARE leads.\n"
    "\n"
    "      * Thread-joining / +1 form (UNCONDITIONAL LEAD): '+1',\n"
    "        'same here', 'same need', 'me too', 'also looking'.\n"
    "\n"
    "  (b) CONCRETE NEED specification — at least one of:\n"
    "      a specific vertical (iGaming/casino/forex/crypto/adult/etc.),\n"
    "      a specific geography (country/region),\n"
    "      a specific payment method (Blik/iDeal/USDT/etc.),\n"
    "      a volume / FTD / STD / approve-rate requirement,\n"
    "      a specific provider whose offering they want to use.\n"
    "\n"
    "EXPLICITLY NOT a lead:\n"
    "\n"
    "  - Due-diligence / reputation checks ('Who worked with X?',\n"
    "    'reviews of X') unless the author also states their own concrete\n"
    "    procurement need.\n"
    "\n"
    "  - Market-pulse / situational questions — research, not\n"
    "    procurement ('situation with X', 'is X still working?',\n"
    "    'what is everyone using?').\n"
    "\n"
    "  - Complaints / blacklist callouts / dispute outreach about past\n"
    "    providers (recovery, not buying).\n"
    "\n"
    "  - Seller-side messages — pitching, offering, advertising:\n"
    "    'we offer', 'we have X available', 'our solution' — even when\n"
    "    ending with 'dm me'.\n"
    "\n"
    "  - Seller inventory pitches — bullet/comma list of capabilities\n"
    "    under headers like 'What we offer:' / 'Our advantages:', often\n"
    "    followed by '@username'. These are ads regardless of\n"
    "    geo/method listed.\n"
    "\n"
    "  - Affiliate / traffic / media-buying requests ('looking for\n"
    "    traffic', 'seeking gambling volumes').\n"
    "\n"
    "  - Single-PSP relationship continuation ('looking for [Brand]\n"
    "    representatives', 'want to resume working with [Brand]').\n"
    "\n"
    "  - Networking / contact-hunt asks without a stated procurement\n"
    "    need ('connect me with X', 'contacts for Y').\n"
    "\n"
    "  - Hiring / staffing requests ('hiring', 'job opening',\n"
    "    'we have a vacancy').\n"
    "\n"
    "  - Advisory / reply voice — author is advising someone else, not\n"
    "    expressing their own need.\n"
    "\n"
    "  - Adjacent-industry asks that aren't payment-service procurement:\n"
    "    consulting, M&A / acquisition, fund-raising, gaming\n"
    "    platform/license deals (unless paired with a payment need).\n"
    "\n"
    "  - Traffic / media-buying requests — even when paired with a vertical\n"
    "    (casino, crypto, betting): 'looking for traffic', 'teams that run\n"
    "    TikTok/FB', 'seeking volumes', 'лить траф', 'ца гнать', 'офера',\n"
    "    'источники трафика', 'команды по заливу' — NOT a lead regardless\n"
    "    of context. The presence of a casino or crypto vertical does NOT\n"
    "    convert a traffic request into a payment lead.\n"
    "\n"
    "  - Brand/operator contact searches: 'контакты казино X', 'contacts for\n"
    "    [Brand]', 'looking for [Brand] representatives', 'SE/DK/MGA licensed\n"
    "    brands', 'контакт прямого рекламодателя' — NOT a lead.\n"
    "\n"
    "  CRITICAL DISAMBIGUATION:\n"
    "  BUYER voice  — speaker WANTS the thing: 'anyone have X' → LEAD.\n"
    "  FINDER voice — speaker wants to FIND PEOPLE who use/work with X:\n"
    "    'who works with X' → NOT a lead.\n"
    "  One-off personal transactions (paying for hotel, visa, tickets) —\n"
    "  individual consumer use, not merchant procurement.\n"
)

V5_01_SHORT_LEAD_DEFINITION = (
    "Messages may be in Russian, Ukrainian, English, or mixed — "
    "apply rules equally.\n"
    "\n"
    "A LEAD is a message from a BUYER in the high-risk payments "
    "ecosystem — an iGaming/casino operator, affiliate, merchant, or "
    "platform — who is actively shopping for a payment service (PSP, "
    "acquirer, payment method, gateway, orchestrator, KYC provider, "
    "etc.) AND signals a concrete need.\n"
    "\n"
    "The message is a LEAD if it has BOTH a buyer-intent signal AND a "
    "concrete need spec.\n"
    "\n"
    "  (a) BUYER-INTENT SIGNAL — any of:\n"
    "\n"
    "      * Explicit search/need verb: 'looking for', 'we need',\n"
    "        'we are seeking', 'open to offers', 'ищу', 'нужен',\n"
    "        'нужно', 'требуется', 'шукаю', 'потрібен'.\n"
    "\n"
    "      * BUYER-possession question — speaker WANTS the thing, not\n"
    "        has it: 'anyone have X', 'who has', 'who can offer',\n"
    "        'у кого есть', 'у кого можна взяти', 'хто займається X',\n"
    "        'є хтось хто робить X'.\n"
    "          CRITICAL: 'we have X' / 'у нас есть X' is SELLER voice\n"
    "          and is NEVER a lead.\n"
    "\n"
    "      * Solicitation form — concrete need + invitation to contact\n"
    "        ('dm me', 'contact me', 'пишите в лс', 'отпишитесь').\n"
    "        Pure listings like 'first-deposit, rebill KZ, dm' ARE leads.\n"
    "\n"
    "      * Thread-joining / +1 form (UNCONDITIONAL LEAD): '+1',\n"
    "        'same here', 'same need', 'me too', 'also looking',\n"
    "        'присоединюсь к запросу', 'тоже интересует'.\n"
    "\n"
    "      * Short follow-up in payment context: 'нужен Ливан',\n"
    "        'нужны фокусы на Аргентину', 'нужен KZ' — treat as LEAD\n"
    "        when the geo/method is a payment market, even if short.\n"
    "\n"
    "  (b) CONCRETE NEED specification — at least one of:\n"
    "      a specific vertical (iGaming/casino/forex/crypto/adult/nutra/\n"
    "      dating/trading/MLM/subscription/call centers (often abbreviated as 'CC', 'кц', 'колл-центр', 'трафик кц')/etc.),\n"
    "      a specific geography (country/region),\n"
    "      a specific payment method (Blik/iDeal/USDT/etc.),\n"
    "      a volume / FTD / STD / approve-rate requirement,\n"
    "      a specific provider whose offering they want to use.\n"
    "\n"
    "EXPLICITLY NOT a lead:\n"
    "\n"
    "  - Due-diligence / reputation checks ('Who worked with X?',\n"
    "    'reviews of X') unless the author also states their own concrete\n"
    "    procurement need.\n"
    "\n"
    "  - Market-pulse / situational questions — research, not\n"
    "    procurement ('situation with X', 'is X still working?',\n"
    "    'what is everyone using?').\n"
    "\n"
    "  - Complaints / blacklist callouts / dispute outreach about past\n"
    "    providers (recovery, not buying).\n"
    "\n"
    "  - Seller-side messages — pitching, offering, advertising:\n"
    "    'we offer', 'we have X available', 'our solution', 'I provide'\n"
    "    — even when ending with 'dm me'.\n"
    "\n"
    "  - Seller inventory pitches — bullet/comma list of capabilities\n"
    "    under headers like 'What we offer:' / 'Our advantages:', often\n"
    "    followed by '@username'. These are ads regardless of\n"
    "    geo/method listed.\n"
    "\n"
    "  - P2P crypto / OTC exchange — personal or bulk crypto purchase\n"
    "    without business context: 'need USDT', 'buy USDT TRC20',\n"
    "    'INR to USDT', 'need bulk USDT', 'USDT TRC20 на постоянной\n"
    "    основе', 'need USDT exchanger', 'gaming company needs USDT\n"
    "    supplier', 'game funds USDT' — this is currency exchange, NOT\n"
    "    payment-service procurement. Volume, recurring cadence, or a\n"
    "    company/gaming framing alone do NOT make it a lead. Exception:\n"
    "    ONLY when crypto is the SETTLEMENT CURRENCY for a requested\n"
    "    PAYMENT SERVICE ('casino settlement in USDT via a PSP', 'need\n"
    "    a gateway accepting USDT') — not when the message is about\n"
    "    sourcing/buying the crypto asset itself.\n"
    "\n"
    "  - Bank account / drop purchases: 'куплю сбер', 'возьму сбер 18+',\n"
    "    'ищу дропа под прием денег', 'need corporate account [bank list]',\n"
    "    'buying bank accounts' — acquiring bank accounts or recruiting\n"
    "    money mules is NOT payment-service procurement.\n"
    "\n"
    "  - Agent / cardholder recruitment: 'looking for P2P agents',\n"
    "    'searching for cardholders', 'need Indian agents/traders',\n"
    "    'looking for Four Parties agents', 'searching for stable\n"
    "    cardholder' — seller recruiting infrastructure partners,\n"
    "    NOT a buyer looking for PSP.\n"
    "\n"
    "  - Affiliate / traffic / media-buying requests: 'looking for\n"
    "    traffic', 'teams that run TikTok/FB', 'seeking volumes',\n"
    "    'лить траф' — NOT a lead regardless of vertical.\n"
    "\n"
    "  - Brand/operator contact searches: 'контакты казино X',\n"
    "    'contacts for [Brand]', 'SE/DK/MGA licensed brands' — NOT a lead.\n"
    "\n"
    "  - Single-PSP relationship continuation ('looking for [Brand]\n"
    "    representatives', 'want to resume working with [Brand]').\n"
    "\n"
    "  - Networking / contact-hunt asks without a stated procurement\n"
    "    need ('connect me with X', 'contacts for Y').\n"
    "\n"
    "  - Hiring / staffing requests ('hiring', 'job opening',\n"
    "    'we have a vacancy').\n"
    "\n"
    "  - Advisory / reply voice — author is advising someone else,\n"
    "    not expressing their own need.\n"
    "\n"
    "  - Adjacent-industry asks that aren't payment-service procurement:\n"
    "    consulting, M&A / acquisition, fund-raising, gaming\n"
    "    platform/license deals (unless paired with a payment need).\n"
    "\n"
    "  CRITICAL DISAMBIGUATION:\n"
    "  BUYER voice  — speaker WANTS the thing: 'anyone have X' → LEAD.\n"
    "  FINDER voice — speaker wants to FIND PEOPLE who use/work with X:\n"
    "    'who works with X' → NOT a lead.\n"
    "  AGENT RECRUITER — seller looking for infrastructure partners:\n"
    "    'looking for P2P agents/cardholders' → NOT a lead.\n"
    "  One-off personal transactions (paying for hotel, visa, tickets) —\n"
    "  individual consumer use, not merchant procurement.\n"
)

BY_VERSION: dict[str, str] = {
    "v3": V3_LEAD_DEFINITION,
    "v5": V5_LEAD_DEFINITION,
    "v6": V6_LEAD_DEFINITION,
    "v5-multilang": V5_MULTILANG_LEAD_DEFINITION,
    "v5-short": V5_SHORT_LEAD_DEFINITION,
    "v5-01-short": V5_01_SHORT_LEAD_DEFINITION,
}
